---
galaxy_info:
  role_name: python
  author: xhinhellhx
  description: Installs a Python version using pyenv
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies:
  - role: pyenv
