#!/usr/bin/env bash
#
# provision.sh — interactively pick a container engine, generate the playbook,
# and apply it with ansible-playbook.
#
# This script is the source of truth for the top-level playbook (there is no
# committed site.yml). It writes a temporary playbook listing every role plus
# the chosen container engine, then hands it to ansible-playbook.
#
# Required Galaxy collections (requirements.yml) are installed automatically
# before the playbook runs; skip that step with --skip-galaxy.
#
# Picked variables (currently just the container engine) are remembered in a
# local state file (.provision.env, git-ignored), so later runs reuse them
# without prompting. Force a fresh pick with --reconfigure.
#
# Any extra arguments are forwarded to ansible-playbook, e.g.:
#   ./provision.sh -K --check --diff
#
# Non-interactive override: set CONTAINER_ENGINE=docker|podman to skip the menu.
# Precedence: CONTAINER_ENGINE env var > saved state > interactive prompt.

# Re-exec under bash if started with another shell (e.g. `zsh provision.sh`):
# the interactive menu relies on bash's single-key `read -rsn1`.
if [ -z "${BASH_VERSION:-}" ]; then
	exec bash "$0" "$@"
fi

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Persisted picks from previous runs (sourced as KEY=value shell assignments).
STATE_FILE="${SCRIPT_DIR}/.provision.env"

# Galaxy collections the playbook depends on (e.g. community.general, which
# provides homebrew/homebrew_cask/pipx/git_config used across the roles).
REQUIREMENTS="${SCRIPT_DIR}/requirements.yml"

# Roles applied to every workstation, in a readable top-to-bottom order. The
# finer ordering is enforced by each role's meta/main.yml `dependencies`
# (homebrew, zsh_config, …), so this list only needs to be roughly sensible.
# The container engine (docker | podman) is appended at runtime — keep it out
# of this list.
COMMON_ROLES=(
	homebrew
	zsh
	oh_my_zsh
	zsh_config
	powerlevel10k
	zsh_autosuggestions
	zsh_syntax_highlighting
	oh_my_zsh_plugins
	autoswitch_virtualenv
	nerd_fonts
	ghostty
	git_config
	neovim
	htop
	pre_commit
	shellcheck
	shfmt
	nvm
	node
	pyenv
	python
	golang
	golangci_lint
	goreleaser
	terraform
	helm
	gcloud
	glab
	plantuml
	claude_code
)

# --- Colors (disabled when not a TTY or NO_COLOR is set) ----------------------
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
	BOLD=$'\033[1m'
	DIM=$'\033[2m'
	CYAN=$'\033[36m'
	GREEN=$'\033[32m'
	YELLOW=$'\033[33m'
	RED=$'\033[31m'
	RESET=$'\033[0m'
else
	BOLD=''
	DIM=''
	CYAN=''
	GREEN=''
	YELLOW=''
	RED=''
	RESET=''
fi

info() { printf '%s==>%s %s\n' "${GREEN}${BOLD}" "${RESET}" "$*"; }
warn() { printf '%s==>%s %s\n' "${YELLOW}${BOLD}" "${RESET}" "$*" >&2; }
die() {
	printf '%serror:%s %s\n' "${RED}${BOLD}" "${RESET}" "$*" >&2
	exit 1
}

# --- Numbered menu ------------------------------------------------------------
# Usage: menu "Question" "Option A" "Option B" ...; result index in $MENU_CHOICE.
# Uses a plain line-read (no raw mode / cursor escapes), so it behaves the same
# in every terminal and shell.
MENU_CHOICE=0
menu() {
	local prompt="$1"
	shift
	local options=("$@")
	local count=${#options[@]}
	local i choice

	# Non-interactive (piped stdin): pick the first option.
	if [[ ! -t 0 ]]; then
		MENU_CHOICE=0
		return
	fi

	printf '%s%s%s\n' "${BOLD}" "$prompt" "${RESET}"
	for i in "${!options[@]}"; do
		printf '  %s%d)%s %s\n' "${CYAN}${BOLD}" "$((i + 1))" "${RESET}" "${options[i]}"
	done

	while true; do
		printf '%s➜ choose [1-%d] (default 1):%s ' "${BOLD}" "$count" "${RESET}"
		read -r choice || {
			choice=1
			break
		}
		choice="${choice:-1}"
		if [[ "$choice" =~ ^[0-9]+$ ]] && ((choice >= 1 && choice <= count)); then
			break
		fi
		warn "Please enter a number between 1 and ${count}."
	done
	MENU_CHOICE=$((choice - 1))
}

# --- Playbook generation ------------------------------------------------------
# Usage: generate_playbook <engine> <output-file>
# Writes the full top-level playbook: every common role followed by the chosen
# container engine.
generate_playbook() {
	local engine="$1" out="$2" role
	{
		printf -- '---\n'
		printf '# Generated by provision.sh — do not edit by hand.\n'
		printf '# Container engine: %s\n' "$engine"
		printf -- '- name: Configure work environment\n'
		printf '  hosts: workstations\n'
		printf '  gather_facts: true\n'
		printf '  roles:\n'
		for role in "${COMMON_ROLES[@]}" "$engine"; do
			printf '    - %s\n' "$role"
		done
	} >"$out"
}

# --- State --------------------------------------------------------------------
# Persist the picked variables so the next run can reuse them. The file is a
# plain list of KEY=value assignments, sourced on the next run.
save_state() {
	umask 077
	{
		printf '# Generated by provision.sh — remembered picks. Safe to delete.\n'
		printf 'CONTAINER_ENGINE=%s\n' "$engine"
	} >"$STATE_FILE"
}

# --- Sanity checks ------------------------------------------------------------
command -v ansible-playbook >/dev/null 2>&1 \
	|| die "ansible-playbook not found. Install Ansible first."

printf '\n%s%s  workenv provisioner%s\n\n' "${BOLD}" "${CYAN}" "${RESET}"

# --- Parse our own flags (everything else is forwarded to ansible-playbook) ---
reconfigure=0
skip_galaxy=0
PLAYBOOK_ARGS=()
for arg in "$@"; do
	case "$arg" in
		--reconfigure) reconfigure=1 ;;
		--skip-galaxy) skip_galaxy=1 ;;
		*) PLAYBOOK_ARGS+=("$arg") ;;
	esac
done

# --- Pick the container engine ------------------------------------------------
# Precedence: CONTAINER_ENGINE env var > saved state > interactive prompt.
# Capture the env var before sourcing state, so the file can't clobber it.
engine="${CONTAINER_ENGINE:-}"

if [[ -z "$engine" && "$reconfigure" -eq 0 && -f "$STATE_FILE" ]]; then
	# shellcheck source=/dev/null
	source "$STATE_FILE"
	engine="${CONTAINER_ENGINE:-}"
	[[ -n "$engine" ]] && info "Reusing saved container engine (--reconfigure to change)."
fi

if [[ -z "$engine" ]]; then
	menu "Which container engine do you want to use?" \
		"Docker  — Docker Engine / Desktop" \
		"Podman  — daemonless, rootless-friendly"
	case "$MENU_CHOICE" in
		0) engine="docker" ;;
		1) engine="podman" ;;
	esac
fi

case "$engine" in
	docker | podman) ;;
	*) die "Invalid CONTAINER_ENGINE='${engine}' (expected docker or podman)" ;;
esac
info "Container engine: ${BOLD}${engine}${RESET}"

# Remember the pick for next time.
save_state
info "Saved picks to ${DIM}${STATE_FILE}${RESET}"

# --- Generate the temporary playbook ------------------------------------------
TMP_PLAYBOOK="$(mktemp -t workenv-site.XXXXXX)"
mv "$TMP_PLAYBOOK" "${TMP_PLAYBOOK}.yml"
TMP_PLAYBOOK="${TMP_PLAYBOOK}.yml"
trap 'rm -f "$TMP_PLAYBOOK"' EXIT

generate_playbook "$engine" "$TMP_PLAYBOOK"
info "Generated playbook: ${DIM}${TMP_PLAYBOOK}${RESET}"

# --- Install Galaxy dependencies ----------------------------------------------
# The roles reference modules from community.general (homebrew, homebrew_cask,
# pipx, git_config). Ansible resolves a task's module *before* evaluating its
# `when:`, so the collection must be present on every platform — even where the
# homebrew tasks are skipped. Install it up front to avoid "couldn't resolve
# module/action" errors.
if [[ "$skip_galaxy" -eq 0 ]]; then
	if [[ -f "$REQUIREMENTS" ]]; then
		command -v ansible-galaxy >/dev/null 2>&1 \
			|| die "ansible-galaxy not found. Install Ansible first, or pass --skip-galaxy."
		info "Installing Galaxy collections from ${DIM}${REQUIREMENTS}${RESET}"
		ansible-galaxy collection install -r "$REQUIREMENTS"
	else
		warn "No requirements.yml at ${REQUIREMENTS}; skipping Galaxy install."
	fi
else
	info "Skipping Galaxy collection install (--skip-galaxy)."
fi

# --- Apply --------------------------------------------------------------------
cd "$SCRIPT_DIR"
export ANSIBLE_ROLES_PATH="${SCRIPT_DIR}/roles"
info "Applying playbook…"
# Not exec'd, so the EXIT trap can clean up the temporary playbook.
# ${PLAYBOOK_ARGS[@]+...} guards against an empty array under `set -u`.
ansible-playbook -i "${SCRIPT_DIR}/inventory/hosts.yml" "$TMP_PLAYBOOK" \
	${PLAYBOOK_ARGS[@]+"${PLAYBOOK_ARGS[@]}"}
