---
galaxy_info:
  role_name: zsh_autosuggestions
  author: xhinhellhx
  description: Installs and enables the zsh-autosuggestions plugin
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies:
  - role: zsh_config
