---
galaxy_info:
  role_name: plantuml
  author: xhinhellhx
  description: Installs PlantUML (diagrams from text)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies:
  - role: homebrew
    when: ansible_system == "Darwin"
