---
galaxy_info:
  role_name: dockle
  author: xhinhellhx
  description: Installs dockle (container image linter)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies:
  - role: homebrew
    when: ansible_facts['system'] == "Darwin"
