---
galaxy_info:
  role_name: nvm
  author: xhinhellhx
  description: Installs nvm (Node Version Manager)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies: []
