---
# Default variables for the yamlfmt role.

# renovate: datasource=github-releases depName=google/yamlfmt extractVersion=^v(?<version>.+)$
yamlfmt_version: "0.21.0"
yamlfmt_install_dir: "/usr/local/bin"
yamlfmt_arch: "{{ 'arm64' if ansible_facts['architecture'] in ['aarch64', 'arm64'] else 'x86_64' }}"
yamlfmt_archive: "yamlfmt_{{ yamlfmt_version }}_Linux_{{ yamlfmt_arch }}.tar.gz"
yamlfmt_repo: "https://github.com/google/yamlfmt"
yamlfmt_download_url: "{{ yamlfmt_repo }}/releases/download/v{{ yamlfmt_version }}/{{ yamlfmt_archive }}"
