---
galaxy_info:
  role_name: zsh
  author: xhinhellhx
  description: Installs zsh and sets it as the default shell
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies: []
