---
# Install bubblewrap, a Linux namespaces sandboxing tool.

- name: Install bubblewrap (Debian/Ubuntu)
  ansible.builtin.apt:
    name: bubblewrap
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install bubblewrap (RHEL family)
  ansible.builtin.dnf:
    name: bubblewrap
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"
