---
galaxy_info:
  role_name: max_open_files
  author: xhinhellhx
  description: Raises the maximum open file descriptors limit
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: MacOSX
    - name: Debian
    - name: Ubuntu
    - name: EL
dependencies: []
